[package]
name = "SeaPad"
version = "1.0.0"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "testnet" }

[addresses]
seapad =  "0x00"
iota =  "0x02"


# staking admin
treasury_admin = "0xf444c3e3bdf826f292357ad9b05fda3fc3c1dc3010b2a408e120f574301881f9"
stake_emergency_admin = "0xf444c3e3bdf826f292357ad9b05fda3fc3c1dc3010b2a408e120f574301881f9"

# staking test addresses.
treasury = "0x13"
emergency = "0x14"
alice = "0x15"
bob = "0x16"